name: Continuous Integration
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
env:
  APP_NAME: projects
  NODE_OPTIONS: --max_old_space_size=4096
  NODE_VERSION: 22.21.1
concurrency:
  # Prevent parallel builds of the same branch
  group: cicd-${{ github.ref }}
  cancel-in-progress: false
jobs:
  requirements:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Export npm store directory as an environment variable
        shell: bash
        run: |
          echo "STORE_PATH=$(npm config get cache)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup npm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-npm-store-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-store-

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test unit
        run: npm run test

      # Images are published to ghcr.io by ghcr.yml
      - name: Build
        run: npm run build
